apiVersion: v1
kind: Service
metadata:
  name: webconsole
  namespace: {{.Values.global.namespace}}
spec:
  type: NodePort
  selector:
    app: {{.Values.activemq.app}}
  ports:
  - port: 8161
    targetPort: 8161
    nodePort: 30161