apiVersion: v1
kind: Service
metadata:
  name: activemq-service
  namespace: {{.Values.global.namespace}}
spec:
  type: ClusterIP
  selector:
    app: {{.Values.activemq.app}}
  ports:
  - port: 61613
    targetPort: 61613
    protocol: TCP